# Generated by Django 4.2.20 on 2026-05-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conhecimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artigos', to='conhecimento.tag', verbose_name='Tags'),
        ),
    ]
