# Generated by Django 4.2.20 on 2026-07-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conhecimento', '0002_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
