# Generated by Django 4.2.20 on 2026-07-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conhecimento', '0003_remove_artigo_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-visualizacoes', '-atualizado_em'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
    ]
