# Generated by Django 4.2.20 on 2026-05-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True, verbose_name='Patrimônio')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='Hostname')),
                ('categoria', models.CharField(choices=[('computador', 'Computador'), ('notebook', 'Notebook'), ('impressora', 'Impressora'), ('monitor', 'Monitor'), ('roteador', 'Roteador'), ('switch', 'Switch'), ('outro', 'Outro')], default='computador', max_length=20, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('processador', models.CharField(blank=True, max_length=200, verbose_name='Processador')),
                ('memoria_ram', models.CharField(blank=True, max_length=50, verbose_name='Memória RAM')),
                ('armazenamento', models.CharField(blank=True, max_length=200, verbose_name='Armazenamento')),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('mac_address', models.CharField(blank=True, max_length=50, verbose_name='MAC Address')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo'), ('descartado', 'Descartado')], default='ativo', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='inventario.equipamento')),
            ],
            options={
                'verbose_name': 'Histórico do Equipamento',
                'verbose_name_plural': 'Históricos dos Equipamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
