# Generated by Django 4.2.20 on 2026-07-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_historicoequipamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/', verbose_name='Imagem (NF/Produto)'),
        ),
    ]
