# Generated by Django 4.2.20 on 2026-07-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_equipamento_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='localizacao',
            new_name='setor',
        ),
    ]
