# Generated by Django 4.2.20 on 2026-07-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_localizacao_to_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='setor',
            field=models.CharField(choices=[('apoio', 'APOIO'), ('atendimento', 'ATENDIMENTO'), ('comunicacao', 'COMUNICAÇÃO'), ('consorcio', 'CONSÓRCIO'), ('convenios', 'CONVÊNIOS'), ('educacao_permanente', 'EDUCAÇÃO PERMANENTE'), ('gerencia', 'GERÊNCIA'), ('iness', 'INESS'), ('nac', 'NAC'), ('rh', 'RH'), ('secretaria', 'SECRETARIA'), ('sinam', 'SINAM'), ('ti', 'T.I'), ('tesouraria', 'TESOURARIA')], default='ti', max_length=200, verbose_name='Setor'),
        ),
    ]
