# Generated by Django 4.2.20 on 2026-07-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_equipamento_imagem_alter_equipamento_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.User', verbose_name='Responsável'),
        ),
    ]
