# Generated by Django 4.2.20 on 2026-07-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('categoria', models.CharField(choices=[('material_limpeza', 'Material de Limpeza'), ('material_expediente', 'Material de Expediente'), ('material_construcao', 'Material de Construção'), ('tintas', 'Tintas'), ('engenharia_obra', 'Engenharia e Obras'), ('madeireira', 'Madeireira'), ('vidracaria', 'Vidraçaria e Alumínio'), ('marcenaria', 'Marcenaria e Divisórias'), ('material_eletrico', 'Material Elétrico e Câmeras'), ('eletricista', 'Eletricista'), ('ar_condicionado', 'Ar Condicionado'), ('poda', 'Serviço de Poda'), ('limpeza_carpete', 'Limpeza de Carpete e Cadeiras'), ('cadeira_rodas', 'Cadeira de Rodas e Maca'), ('manutencao', 'Manutenção'), ('grafica', 'Serviço Gráfico'), ('prestador_servico', 'Prestador de Serviços')], default='prestador_servico', max_length=30, verbose_name='Categoria')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Vendedor')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=50, unique=True, verbose_name='Nº Patrimônio')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Bem')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('categoria', models.CharField(choices=[('moveis', 'Móveis'), ('equipamentos', 'Equipamentos'), ('informatica', 'Informática'), ('eletrodomesticos', 'Eletrodomésticos'), ('ferramentas', 'Ferramentas'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Categoria')),
                ('setor', models.CharField(choices=[('apoio', 'APOIO'), ('atendimento', 'ATENDIMENTO'), ('comunicacao', 'COMUNICAÇÃO'), ('consorcio', 'CONSÓRCIO'), ('convenios', 'CONVÊNIOS'), ('educacao_permanente', 'EDUCAÇÃO PERMANENTE'), ('gerencia', 'GERÊNCIA'), ('iness', 'INESS'), ('nac', 'NAC'), ('rh', 'RH'), ('secretaria', 'SECRETARIA'), ('sinam', 'SINAM'), ('ti', 'T.I'), ('tesouraria', 'TESOURARIA')], default='apoio', max_length=200, verbose_name='Setor')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('situacao', models.CharField(choices=[('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('baixado', 'Baixado'), ('disponivel', 'Disponível')], default='em_uso', max_length=20, verbose_name='Situação')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Aquisição (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='apoio/patrimonio/', verbose_name='Nota Fiscal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('categoria', models.CharField(choices=[('alimentos', 'Alimentos'), ('limpeza', 'Limpeza'), ('escritorio', 'Escritório'), ('higiene', 'Higiene'), ('descartaveis', 'Descartáveis'), ('informatica', 'Informática'), ('ferramentas', 'Ferramentas'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('unidade_medida', models.CharField(choices=[('unidade', 'Unidade'), ('caixa', 'Caixa'), ('pacote', 'Pacote'), ('litro', 'Litro'), ('kg', 'Kg'), ('metro', 'Metro'), ('fardo', 'Fardo'), ('galão', 'Galão')], default='unidade', max_length=20, verbose_name='Unidade de Medida')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Custo (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('motivo', models.CharField(blank=True, choices=[('compra', 'Compra'), ('transferencia', 'Transferência'), ('perda_avaria', 'Perda / Avaria'), ('devolucao_fornecedor', 'Devolução ao fornecedor'), ('consumo_interno', 'Consumo interno'), ('exclusao_produto', 'Exclusão de produto'), ('outro', 'Outro')], max_length=30, verbose_name='Motivo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('saldo_apos', models.IntegerField(default=0, verbose_name='Saldo após')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (R$)')),
                ('nota_fiscal', models.ImageField(blank=True, null=True, upload_to='apoio/movimentacoes/', verbose_name='Nota Fiscal')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apoio.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='apoio.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_apoio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
                name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='apoio.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='apoio.produto')),
            ],
            options={
                'verbose_name': 'Produto-Fornecedor',
                'verbose_name_plural': 'Produtos-Fornecedores',
                'unique_together': {('produto', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='apoio.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico do Produto',
                'verbose_name_plural': 'Históricos dos Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='apoio.patrimonio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico do Patrimônio',
                'verbose_name_plural': 'Históricos dos Patrimônios',
                'ordering': ['-criado_em'],
            },
        ),
    ]
