# Generated by Django 4.2.20 on 2026-05-26 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('manutencao', 'Manutenção'), ('visita', 'Visita Técnica'), ('backup', 'Backup'), ('vencimento', 'Vencimento'), ('reuniao', 'Reunião'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo')),
                ('cor', models.CharField(choices=[('#0d6efd', 'Azul'), ('#dc3545', 'Vermelho'), ('#198754', 'Verde'), ('#ffc107', 'Amarelo'), ('#6f42c1', 'Roxo'), ('#fd7e14', 'Laranja')], default='#0d6efd', max_length=7, verbose_name='Cor')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('dia_todo', models.BooleanField(default=False, verbose_name='Dia todo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
