# Generated by Django 4.2.20 on 2026-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em Andamento'), ('resolvido', 'Resolvido')], default='aberto', max_length=15, verbose_name='Status'),
        ),
    ]
