# Generated by Django 4.2.20 on 2026-06-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_remove_fechado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('rede', 'Rede'), ('email', 'E-mail'), ('impressora', 'Impressora'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria'),
        ),
    ]
