# Generated by Django 4.2.20 on 2026-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='imagem_tecnica',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/tecnicas/', verbose_name='Imagem Técnica'),
        ),
    ]
