# Generated by Django 4.2.20 on 2026-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_imagem_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(blank=True, choices=[('hardware', 'Hardware'), ('software', 'Software'), ('rede', 'Rede'), ('email', 'E-mail'), ('impressora', 'Impressora'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
    ]
