# Generated by Django 4.2.20 on 2026-07-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_portal_campos_em_branco'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='imagem_solicitante',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/solicitante/', verbose_name='Imagem do Solicitante'),
        ),
    ]
