# Generated by Django 4.2.20 on 2026-07-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_alter_chamado_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('rede', 'Rede'), ('email', 'E-mail'), ('impressora', 'Impressora'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria'),
        ),
    ]
