# Generated by Django 4.2.20 on 2026-07-15 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Ramal')),
                ('setor', models.CharField(choices=[('apoio', 'APOIO'), ('atendimento', 'ATENDIMENTO'), ('comunicacao', 'COMUNICAÇÃO'), ('consorcio', 'CONSÓRCIO'), ('convenios', 'CONVÊNIOS'), ('educacao_permanente', 'EDUCAÇÃO PERMANENTE'), ('gerencia', 'GERÊNCIA'), ('iness', 'INESS'), ('nac', 'NAC'), ('rh', 'RH'), ('secretaria', 'SECRETARIA'), ('sinam', 'SINAM'), ('ti', 'T.I'), ('tesouraria', 'TESOURARIA')], default='ti', max_length=100, verbose_name='Setor')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/avatares/', verbose_name='Avatar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
