# Generated by Django 4.2.20 on 2026-05-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ramal'),
        ),
    ]
