# Generated by Django 4.2.20 on 2026-06-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tema_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tema',
        ),
    ]
