# Generated by Django 4.2.20 on 2026-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('ti', 'TI'), ('usuario', 'Usuário')], default='usuario', max_length=20, verbose_name='Cargo'),
        ),
    ]
