# Generated by Django 4.2.20 on 2026-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_simplificar_cargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='setor',
            field=models.CharField(choices=[('apoio', 'APOIO'), ('atendimento', 'ATENDIMENTO'), ('comunicacao', 'COMUNICAÇÃO'), ('consorcio', 'CONSÓRCIO'), ('convenios', 'CONVÊNIOS'), ('educacao_permanente', 'EDUCAÇÃO PERMANENTE'), ('gerencia', 'GERÊNCIA'), ('iness', 'INESS'), ('nac', 'NAC'), ('rh', 'RH'), ('secretaria', 'SECRETARIA'), ('sinam', 'SINAM'), ('ti', 'T.I'), ('tesouraria', 'TESOURARIA')], default='ti', max_length=100, verbose_name='Setor'),
        ),
    ]
