# Generated by Django 4.2.20 on 2026-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfil_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('ti', 'T.I'), ('usuario', 'Usuário')], default='usuario', max_length=20, verbose_name='Cargo'),
        ),
    ]
